/***
Put objects on stage.

1. Given:
    *a camera universe location
    *a background actor universe location
    *a background actor screen location
    *Camera up, right, sky, and angle
   Find:
    *Location and look-at that put the background actor at the designated location

2. Given:
    *Location and look-at
    *camera up, right, sky, and angle

2. Given:
    *a camera universe location
    *stage basis vectors
    *camera up, right, and angle
    *foreground actor distance from camera
    *foreground actor position
   Find:
    *foreground actor